# Parte 1: Visualización con Plotly

## 1. Cargar el dataset, leerlo y mostrar las dimensiones y las 5 primeras filas

In [1]:
import pandas as pd
import plotly.express as px

tabla = pd.read_csv("C:\\Users\\User\\Documents\\Github\\Python---Grupo-4\\assignment_3\\datos\\tabla_final.csv", dtype={"ubigeo": str}) #Cargo el archivo

tabla.shape # Veo las dimensiones de la tabla

(25, 9)

In [2]:
tabla.head(5) # Veo las primeras 5 filas de la tabla

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas
0,01,Amazonas,Chachapoyas,-6.23169,-77.86903,427.9,0,8,4
1,02,Áncash,Huaraz,-9.52614,-77.52869,1415.9,11,8,6
2,03,Apurímac,Abancay,-13.63426,-72.88380,820.0,3,7,2
3,04,Arequipa,Arequipa,-16.39899,-71.53747,439.4,3,8,2
4,05,Ayacucho,Ayacucho,-13.16380,-74.22345,500.8,1,8,4

## 2. Tema o pregunta a abordar 

Nuestra pregunta serán las siguientes: 

a) ¿Cuáles fueron los 10 departamentos que acumularon más lluvia (en mm) durante el periodo de enero a mayo del 2025? 
b) ¿Existe relación entre la cantidad de lluvia acumulada en un departameto y el número de declaratorias de emergencia recibidas durante los meses de enero a mayo del 2025?
c) ¿Cuánta cantidad de lluvia acumuló la mayoría de departamentos durante el periodo analizado?

Para responder lo anterior, se usarán las columnas "departamento", "declaratorias" y "lluvia_total_mm" del dataset elegido.

## 3. Crear tres gráficos interactivos con Plotly

In [26]:
# Grafico de barras de la cantidad de lluvia por departamento

lluvia_mm = tabla.sort_values("lluvia_total_mm", ascending=False).head(10) # Ordeno la tabla por cantidad de lluvia y me quedo con los 10 primeros

graf_1 = px.bar(lluvia_mm, x="departamento", y="lluvia_total_mm",
                    title="Los 10 departamentos con mayor cantidad de lluvia en mm (Enero 2025 - Mayo 2025)",
                    labels={"departamento": "Departamento", "lluvia_total_mm": "Cantidad de lluvia (mm)"},
                    color="lluvia_total_mm", color_continuous_scale="teal")

graf_1.update_layout(coloraxis_showscale=False)

graf_1.show()

En el gráfico se puede observar que los 10 departamentos con mayor cantidad de lluvia acumulada en mm, durante los meses de enero a mayo del 2025, fueron Loreto, Madre de Dios, Áncash, Junín, Ucayali, Puno, San Martín, Huancavelica, Cajamarca y Pasco.

In [24]:
# Grafico de dispersión de la relación entre la cantidad de lluvia y las declaratorias según departamento

decla_lluvia =px.scatter(tabla[tabla["declaratorias"] > 0],
                x="lluvia_total_mm", y="declaratorias",
                hover_name="departamento",
                title="Relación entre cantidad de lluvia y declaratorias según departamento (Enero 2025 - Mayo 2025)",
                labels={"lluvia_total_mm": "Cantidad de lluvia (mm)", "declaratorias": "Cantidad de declaratorias"})

decla_lluvia.show()

Con el gráfico de dispersión se puede concluir que no existe una relación clara entre la cantidad de lluvia en un departamento y el número de declaratorias de emergencia emitidos, ya que los puntos están dispersos sin formar una tendencia.

In [15]:
# Histograma del número de departamentos según la cantidad de lluvia

hist_lluvia = px.histogram(tabla, x="lluvia_total_mm",
                nbins=10,
                color_discrete_sequence=["teal"],
                title="Número de departamentos según la cantidad de lluvia en mm (Enero 2025 - Mayo 2025)",
                labels={"lluvia_total_mm": "Cantidad de lluvia (mm)"})

hist_lluvia.update_layout(yaxis_title="Cantidad de departamentos", bargap=0.05)

hist_lluvia.show()

A partir del histograma, se precisa que la mayoria de departamentos (10) acumuló menos de 500 mm de lluvia, mientras solo dos departamentos presentaron más de 1500 mm de lluvia.

## 4. Verificación rápida

In [16]:
# Gráfico 1: Los 10 departamentos con mayor cantidad de lluvia en mm (Enero 2025 - Mayo 2025)

tabla.sort_values("lluvia_total_mm", ascending=False)[["departamento", "lluvia_total_mm"]].head(10)

     departamento  lluvia_total_mm
15         Loreto           2019.9
16  Madre de Dios           1751.3
1          Áncash           1415.9
11          Junín           1349.1
24        Ucayali           1309.0
20           Puno           1074.4
21     San Martín            943.3
8    Huancavelica            930.4
5       Cajamarca            875.7
18          Pasco            874.2

Se puede comprobar que tanto la tabla como el gráfico muestran los mismos departamentos.

In [21]:
# Gráfico 2: Cantidad de lluvia por declaratorias según departamento (Enero 2025 - Mayo 2025)

# Mostrar los 5 departamentos con mayor cantidad de lluvia
tabla.sort_values("lluvia_total_mm", ascending=False)[["departamento", "lluvia_total_mm", "declaratorias"]].head(5)

     departamento  lluvia_total_mm  declaratorias
15         Loreto           2019.9              8
16  Madre de Dios           1751.3              3
1          Áncash           1415.9              8
11          Junín           1349.1              7
24        Ucayali           1309.0              6

In [22]:
# Mostrar los 5 departamentos con mayor cantidad de declaratorias       
tabla.sort_values("declaratorias", ascending=False)[["departamento", "lluvia_total_mm", "declaratorias"]].head(5)

  departamento  lluvia_total_mm  declaratorias
7        Cusco            801.3              9
0     Amazonas            427.9              8
1       Áncash           1415.9              8
4     Ayacucho            500.8              8
3     Arequipa            439.4              8

In [ ]:
Se puede observar que los departamentos con mayor cantidad de lluvia no necesariamente son los mismos que tienen mayor cantidad de declaratorias, lo que indica que la relación entre la cantidad de lluvia y las declaratorias no es directa y puede depender de otros factores.

In [23]:
# Grafico 3: Número de departamentos según la cantidad de lluvia en mm (Enero 2025 - Mayo 2025)

pd.cut(tabla["lluvia_total_mm"], bins=[0, 500, 1000, 1500, 2000, 2500], include_lowest=True).value_counts().sort_index()

lluvia_total_mm
(-0.001, 500.0]     10
(500.0, 1000.0]      9
(1000.0, 1500.0]     4
(1500.0, 2000.0]     1
(2000.0, 2500.0]     1
Name: count, dtype: int64

Se comprueba que 10 departamentos, es decir, la mayoría presenta hasta 500 mm de lluvia acumulada, mientras solo 2 muestran más de 1500 mm de lluvia acumulada para el periodo analizado.

## 5. Ajustar titulos y etiquetas de los gráficos 

Ya se ha realizado en su respectiva sección

## 6. Exportar uno de los gráficos a formato HTML

In [28]:
# Exporto el gráfico de barras a un archivo HTML

graf_1.write_html("barras_lluvia.html")